### ISSUE TITLE
API for CRUD needs to be updated

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-api-python#3]
The API for CRUD needs to be updated to make it short and more intuitive.

Here's the current API for javascript:
```js
// Insert one / all:
db.insert(col).one(doc).then(res => ...).catch(ex => ...);
db.insert(col).all(docs).then(res => ...).catch(ex => ...);

// Get one / all:
db.get(col).where(whereClause).one().then(res => ...).catch(ex => ...);
db.get(col).where(whereClause).all().then(res => ...).catch(ex => ...);

// Update one / all:
db.update(col).where(whereClause).set(obj).one().then(res => ...).catch(ex => ...);
db.update(col).where(whereClause).set(obj).all().then(res => ...).catch(ex => ...);

// Delete one / all:
db.delete(col).where(whereClause).one().then(res => ...).catch(ex => ...);
db.delete(col).where(whereClause).all().then(res => ...).catch(ex => ...);
```
In the new API there should not be explicit one() and all() method. The API should take the default operation type to be `all` since `one` is used very rarely and also `one` is not available on SQL. However, the user should be able to change the `op` by calling an optional `op` method. The method `apply` will actually trigger the request.

This is the new proposal:
```js
// Insert all:
db.insert(col).docs(docs).apply().then(res => ...).catch(ex => ...);
// Insert one:
db.insert(col).doc(doc).apply().then(res => ...).catch(ex => ...);

// Get all:
db.get(col).where(whereClause).apply().then(res => ...).catch(ex => ...);
// Get one:
db.getOne(col).where(whereClause).apply().then(res => ...).catch(ex => ...);
// Get count:
db.count(col).where(whereClause).apply().then(res => ...).catch(ex => ...);
// Get distinct:
db.distinct(col).where(whereClause).apply().then(res => ...).catch(ex => ...);

// Update all:
db.update(col).where(whereClause).set(obj).apply().then(res => ...).catch(ex => ...);
// Update one:
db.updateOne(col).where(whereClause).set(obj).apply().then(res => ...).catch(ex => ...);
// Upsert:
db.upsert(col).where(whereClause).set(obj).apply().then(res => ...).catch(ex => ...);

// Delete all:
db.delete(col).where(whereClause).apply().then(res => ...).catch(ex => ...);
// Delete one:
db.deleteOne(col).where(whereClause).apply().then(res => ...).catch(ex => ...);
```
This needs to be ported on python

**Comment by Jayesh333** [comment]
So basically the op will be passed in the constructor directly. No need to set it towards the end.

**Comment by AliabbasMerchant** [comment]
Why do we need to explicitly set `op`?  
We already have the `deleteOne`, `getOne` and `updateOne` functions, right?

**Comment by AliabbasMerchant** [comment]
For consistency, shouldn't we have an `insertOne` function also??
So,  
```
// Insert all:
db.insert(col).docs(docs).apply().then(res => ...).catch(ex => ...);
// Insert one:
db.insert_one(col).docs(doc).apply().then(res => ...).catch(ex => ...);
```

**Comment by Jayesh333** [comment]
The problem with that is `docs` method will have to accept an array for `insert` and an object for `insertOne` method. Do you have any suggestions over here? @AliabbasMerchant

**Comment by AliabbasMerchant** [comment]
We can, maybe, rename the method to `set` or `put` or something of that sort. Something that will work in both, singular and plural context.

**Comment by AliabbasMerchant** [comment]
In `db.distinct(col)`, we need a key also, right?  
So where do we specify that?  
Shall I make it `db.distinct('col', key)....`??

**Comment by Jayesh333** [comment]
Very good you asked that question, I totally missed that part. Yes we need a key. We can add it in the `distinct` method but then it would be inconsistent with other methods like `insert`, `get` etc. So let's add a `key` method for accepting key

**Comment by AliabbasMerchant** [comment]
Ok
